"""Conveyor-belt map reconstruction and phase-estimation tools."""

from .detection import (
    DETECTION_MODES,
    detect_particles_from_residual,
    detect_particles_from_residual_hysteresis,
    detection_signal_from_residual,
    normalize_detection_mode,
)
from .period_state import (
    BeltPeriodState,
    fresh_period_state,
    metadata_fields,
    phase_fraction_and_radians,
    require_period_known,
    reused_period_state,
)
from .phase import (
    BeltMotionModel,
    PhaseEstimate,
    PhaseRegistrationConfig,
    PhaseTrajectorySmoothingConfig,
    estimate_phase,
    refine_phase_by_registration,
    render_belt_view,
    smooth_phase_estimates,
)
from .rendering import (
    BeltRegion,
    CleanBeltRender,
    render_expected_clean_belt,
)
from .residual import (
    ResidualConfig,
    ResidualImage,
    estimate_local_noise,
    generate_residual_image,
    render_clean_belt_residual,
)
from .recurrent_artifacts import (
    RecurrentArtifactConfig,
    RecurrentArtifactDetectionScore,
    RecurrentArtifactMap,
    belt_revolution_indices,
    build_recurrent_artifact_map,
    filter_recurrent_artifact_detections,
    score_recurrent_artifact_detections,
    score_recurrent_artifact_detections_excluding_current_revolution,
)
from .tracking import (
    ParticleComponentConfig,
    ParticleDetection,
    ParticleTrack,
    ParticleTrackScore,
    ParticleTrackingConfig,
    ParticleVelocity,
    TrackFilterConfig,
    estimate_particle_velocities_vs_belt,
    extract_particle_detections,
    extract_particle_velocities_vs_belt,
    filter_particle_velocities,
    score_particle_velocities,
    track_particle_detections,
)

__all__ = [
    "BeltMotionModel",
    "BeltPeriodState",
    "BeltRegion",
    "CleanBeltRender",
    "DETECTION_MODES",
    "PhaseEstimate",
    "PhaseRegistrationConfig",
    "PhaseTrajectorySmoothingConfig",
    "ParticleComponentConfig",
    "ParticleDetection",
    "ParticleTrack",
    "ParticleTrackScore",
    "ParticleTrackingConfig",
    "ParticleVelocity",
    "ResidualConfig",
    "ResidualImage",
    "RecurrentArtifactConfig",
    "RecurrentArtifactDetectionScore",
    "RecurrentArtifactMap",
    "TrackFilterConfig",
    "belt_revolution_indices",
    "build_recurrent_artifact_map",
    "detect_particles_from_residual",
    "detect_particles_from_residual_hysteresis",
    "detection_signal_from_residual",
    "normalize_detection_mode",
    "estimate_particle_velocities_vs_belt",
    "estimate_local_noise",
    "estimate_phase",
    "extract_particle_detections",
    "extract_particle_velocities_vs_belt",
    "filter_recurrent_artifact_detections",
    "filter_particle_velocities",
    "fresh_period_state",
    "generate_residual_image",
    "metadata_fields",
    "phase_fraction_and_radians",
    "refine_phase_by_registration",
    "render_clean_belt_residual",
    "render_belt_view",
    "require_period_known",
    "reused_period_state",
    "smooth_phase_estimates",
    "render_expected_clean_belt",
    "score_particle_velocities",
    "score_recurrent_artifact_detections",
    "score_recurrent_artifact_detections_excluding_current_revolution",
    "track_particle_detections",
]