"""Conveyor-belt map reconstruction and phase-estimation tools."""

from .detection import detect_particles_from_residual
from .phase import (
    BeltMotionModel,
    PhaseEstimate,
    PhaseRegistrationConfig,
    estimate_phase,
    refine_phase_by_registration,
    render_belt_view,
)
from .rendering import (
    BeltRegion,
    CleanBeltRender,
    render_expected_clean_belt,
)
from .residual import (
    ResidualConfig,
    ResidualImage,
    estimate_local_noise,
    generate_residual_image,
    render_clean_belt_residual,
)
from .recurrent_artifacts import (
    RecurrentArtifactConfig,
    RecurrentArtifactDetectionScore,
    RecurrentArtifactMap,
    belt_revolution_indices,
    build_recurrent_artifact_map,
    filter_recurrent_artifact_detections,
    score_recurrent_artifact_detections,
)
from .tracking import (
    ParticleComponentConfig,
    ParticleDetection,
    ParticleTrack,
    ParticleTrackScore,
    ParticleTrackingConfig,
    ParticleVelocity,
    TrackFilterConfig,
    estimate_particle_velocities_vs_belt,
    extract_particle_detections,
    extract_particle_velocities_vs_belt,
    filter_particle_velocities,
    score_particle_velocities,
    track_particle_detections,
)

__all__ = [
    "BeltMotionModel",
    "BeltRegion",
    "CleanBeltRender",
    "PhaseEstimate",
    "PhaseRegistrationConfig",
    "ParticleComponentConfig",
    "ParticleDetection",
    "ParticleTrack",
    "ParticleTrackScore",
    "ParticleTrackingConfig",
    "ParticleVelocity",
    "ResidualConfig",
    "ResidualImage",
    "RecurrentArtifactConfig",
    "RecurrentArtifactDetectionScore",
    "RecurrentArtifactMap",
    "TrackFilterConfig",
    "belt_revolution_indices",
    "build_recurrent_artifact_map",
    "detect_particles_from_residual",
    "estimate_particle_velocities_vs_belt",
    "estimate_local_noise",
    "estimate_phase",
    "extract_particle_detections",
    "extract_particle_velocities_vs_belt",
    "filter_recurrent_artifact_detections",
    "filter_particle_velocities",
    "generate_residual_image",
    "refine_phase_by_registration",
    "render_clean_belt_residual",
    "render_belt_view",
    "render_expected_clean_belt",
    "score_particle_velocities",
    "score_recurrent_artifact_detections",
    "track_particle_detections",
]
